import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, Check, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PageHero, SiteFooter, SiteHeader } from '@/components/site-shell';
import { breadcrumbList, StructuredData } from '@/components/structured-data';

export const metadata:Metadata={title:'关于蓝旗鱼 AI',description:'蓝旗鱼 AI 是面向中国企业的 Forward Deployed Engineering 落地团队，负责诊断、MVD、生产部署、采用与交接。',alternates:{canonical:'/about'}};
const method=[['诊断','进入真实流程，核验问题、数据、责任和风险。'],['MVD','用真实数据和使用者验证最小业务闭环。'],['生产部署','接入系统、权限、评估、监控与回退。'],['采用与交接','让一线持续使用，并把运营能力交给企业。'],['复制','只复制已通过证据门的流程和资产。']];
export default function Page(){const schema={'@context':'https://schema.org','@graph':[{'@type':['Organization','ProfessionalService'],'@id':'https://bluefin-ai.cn/#organization',name:'蓝旗鱼 AI',url:'https://bluefin-ai.cn',mainEntityOfPage:'https://bluefin-ai.cn/about',description:metadata.description,founder:{'@id':'https://bluefin-ai.cn/about/arthur-guo#person'},areaServed:{'@type':'Country',name:'中国'},knowsAbout:['企业 AI 落地','Forward Deployed Engineering','最小可行部署 MVD','企业 AI 现场诊断','生产部署与采用']},breadcrumbList([{name:'首页',path:'/'},{name:'关于蓝旗鱼 AI',path:'/about'}])]};return <><SiteHeader/><main><StructuredData data={schema}/><PageHero eyebrow="品牌与品类实体" title="蓝旗鱼 AI，把企业 AI 做到真实业务现场。" intro="蓝旗鱼 AI 是面向中国企业的 FDE 落地团队。我们从昂贵问题和真实数据出发，分阶段完成现场诊断、最小可行部署、生产上线、采用与交接；每一阶段都保留继续、调整、暂停或停止的证据门。"/>
<section className="px-5 py-20 lg:px-10"><div className="mx-auto grid max-w-[1300px] gap-12 lg:grid-cols-2"><div><p className="eyebrow text-[#147e66]">核心品类</p><h2 className="mt-5 text-4xl font-black tracking-[-.04em] lg:text-6xl">企业 AI 落地 / Forward Deployed Engineering</h2><p className="mt-6 text-lg leading-8 text-muted-foreground">FDE 的关键不是工程师“驻场”，而是工程、数据、业务和采用责任在同一个结果闭环中协作。蓝旗鱼不把判断交给咨询报告，也不在问题未定义时接收无边界功能清单。</p><div className="mt-8 flex flex-wrap gap-3"><Button nativeButton={false} render={<Link href="/fde"/>} variant="outline" className="h-12 rounded-none">理解 FDE</Button><Button nativeButton={false} render={<Link href="/services"/>} className="h-12 rounded-none">查看服务阶梯 <ArrowRight/></Button></div></div><div className="grid gap-px bg-foreground/15 sm:grid-cols-2"><div className="bg-[#dff6e6] p-7"><p className="eyebrow text-[#147e66]">服务对象</p><p className="mt-5 text-2xl font-black">有真实数据、真实流程、负责人和结果压力的企业</p></div><div className="bg-[#071817] p-7 text-white"><p className="eyebrow text-[#bff5d1]">核心差异</p><p className="mt-5 text-2xl font-black">工程师直接面对业务结果，并沉淀可复用资产</p></div><div className="bg-white p-7"><p className="eyebrow text-[#147e66]">工作语言</p><p className="mt-5 text-2xl font-black">中文为主，面向中国企业场景</p></div><div className="bg-[#f1eee5] p-7"><p className="eyebrow text-[#8b4a38]">公开边界</p><p className="mt-5 leading-7 text-muted-foreground">“蓝旗鱼 AI”是本站使用的公开品牌名称；具体签约主体、服务地点、费用与责任以双方书面合同为准。</p></div></div></div></section>
<section className="bg-[#071817] px-5 py-20 text-white lg:px-10"><div className="mx-auto max-w-[1300px]"><p className="eyebrow text-[#bff5d1]">交付方法</p><div className="mt-10 grid gap-px bg-white/15 md:grid-cols-5">{method.map(([title,detail],index)=><article key={title} className="bg-[#071817] p-7"><span className="text-xs text-[#bff5d1]">0{index+1}</span><h2 className="mt-8 text-2xl font-black">{title}</h2><p className="mt-3 leading-7 text-white/55">{detail}</p></article>)}</div></div></section>
<section className="px-5 py-20 lg:px-10"><div className="mx-auto grid max-w-[1300px] gap-8 lg:grid-cols-2"><div><p className="eyebrow text-[#147e66]">我们坚持</p><div className="mt-6 space-y-3">{['从正在发生的损失和原始证据开始','在开发前定义基线、阈值、边界和停止条件','把系统放进真实工作流，跟踪采用与结果','区分已验证案例、脱敏记录、任职实践、原型和假设'].map(item=><p key={item} className="flex gap-3 border-t border-foreground/15 py-4 leading-7"><Check className="mt-1 size-5 shrink-0 text-[#147e66]"/>{item}</p>)}</div></div><div className="bg-[#f1eee5] p-8"><p className="eyebrow text-[#8b4a38]">我们不做</p><div className="mt-6 space-y-4">{['泛泛培训替代生产部署','把 Demo 或未授权原型包装成客户成功','没有边界和停止条件的定制外包','一次性“AI 赋能全集团”的空泛承诺'].map(item=><p key={item} className="flex gap-3 leading-7 text-muted-foreground"><X className="mt-1 size-5 shrink-0 text-[#8b4a38]"/>{item}</p>)}</div></div></div></section>
<section className="bg-[#dff6e6] px-5 py-18 lg:px-10"><div className="mx-auto grid max-w-[1300px] gap-10 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="eyebrow text-[#147e66]">负责人和公开责任</p><h2 className="mt-4 text-4xl font-black">郭斌 Arthur</h2><p className="mt-4 max-w-3xl leading-7 text-muted-foreground">企业 AI 系统设计与 FDE 落地实践者。公开经历、任职实践与证据限制在独立人物页说明；本站内容遵循公开编辑与证据政策。</p></div><div className="flex flex-wrap gap-3"><Button nativeButton={false} render={<Link href="/about/arthur-guo"/>} variant="outline" className="h-12 rounded-none bg-transparent">查看 Arthur</Button><Button nativeButton={false} render={<Link href="/editorial-policy"/>} className="h-12 rounded-none">查看编辑政策 <ArrowRight/></Button></div></div></section>
</main><SiteFooter/></>}
