import type { Metadata } from 'next';
import Link from '@/components/safe-link';
import { ArrowRight, Check } from 'lucide-react';
import { ArticleMeta } from '@/components/article-meta';
import { Button } from '@/components/ui/button';
import { PageHero, SiteFooter, SiteHeader } from '@/components/site-shell';
export const metadata:Metadata={title:'Deeper Network 复杂售后调查系统｜生产实践',description:'郭斌 Arthur 在 Deeper Network 任职期间参与的远程取证与专家调查生产实践：问题、流程、结果与证据边界。',alternates:{canonical:'/evidence/production-proof/deeper-network'}};
const before=['客服反复补充环境信息','工程师手动获取设备与日志','调查经验留在少数人脑中','进度和结论分散在消息里','高级工程师承担重复取证工作'];
const after=['问题上下文按模板汇聚','远程取证流程自动运行','历史案例与调查路径可以复用','状态、证据和结论可以追踪','工程师聚焦验证和高风险判断'];
export default function Page(){return <><SiteHeader/><main><PageHero eyebrow="生产实践 · 任职经历" title="把数月的复杂调查，变成可复制的生产流程。" intro="Arthur 在 Deeper Network 任职期间，面对全球设备售后调查中的跨岗位、跨系统和长周期问题，参与建设远程取证系统与专家调查能力。此页证明负责人生产交付经历，不属于蓝旗鱼客户案例。"/><ArticleMeta title="Deeper Network 复杂售后调查系统｜生产实践" description="远程取证、专家调查、工程师验证与生产运行。" path="/evidence/production-proof/deeper-network" status="任职期间生产实践（非蓝旗鱼客户案例）"/>
  <section className="px-5 py-18 lg:px-10"><div className="mx-auto max-w-[1300px]"><div className="grid gap-px bg-foreground/15 sm:grid-cols-3"><article className="bg-background p-8"><span className="text-xs text-muted-foreground">产品覆盖</span><strong className="mt-3 block text-4xl font-black">150+</strong><p className="mt-2 text-muted-foreground">国家和地区</p></article><article className="bg-background p-8"><span className="text-xs text-muted-foreground">设备规模</span><strong className="mt-3 block text-4xl font-black">20 万+</strong><p className="mt-2 text-muted-foreground">台设备</p></article><article className="bg-background p-8"><span className="text-xs text-muted-foreground">复杂问题原周期</span><strong className="mt-3 block text-4xl font-black">数周至数月</strong><p className="mt-2 text-muted-foreground">跨至少四类岗位</p></article></div><div className="mt-18 grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow text-[#147e66]">原始问题</p><h2 className="mt-5 text-4xl font-black tracking-[-.04em] lg:text-6xl">一句“不能用”，背后是完整调查链。</h2></div><div className="grid gap-px bg-foreground/15 sm:grid-cols-5">{['客户报障','客服补信息','技术取证','研发调查','客户验证'].map((step,index)=><article key={step} className="bg-background p-5"><span className="text-xs text-[#147e66]">0{index+1}</span><h3 className="mt-8 font-black">{step}</h3></article>)}</div></div></div></section>
  <section className="bg-[#071817] px-5 py-20 text-white lg:px-10"><div className="mx-auto max-w-[1300px]"><p className="eyebrow text-[#bff5d1]">工作流重构</p><h2 className="mt-5 max-w-4xl text-4xl font-black tracking-[-.04em] lg:text-6xl">上下文 → 证据 → 经验 → 初判 → 验证</h2><div className="mt-12 grid gap-px bg-white/15 md:grid-cols-5">{[['汇聚上下文','设备、国家、时间和版本'],['自动取证','状态、日志和现场信息'],['关联历史','复用案例与调查路径'],['AI 初判','形成标准调查记录'],['工程师验证','确认结论并回写结果']].map(([title,detail],index)=><article key={title} className="bg-[#071817] p-6"><span className="text-xs text-[#bff5d1]">0{index+1}</span><h3 className="mt-7 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-white/55">{detail}</p></article>)}</div><p className="mt-8 border-l-2 border-[#bff5d1] pl-5 text-white/70">AI 负责信息整理和初步判断；工程师负责证据验证、结论确认和高风险决策。</p></div></section>
  <section className="px-5 py-20 lg:px-10"><div className="mx-auto max-w-[1300px]"><div className="grid gap-8 lg:grid-cols-2"><div className="border border-foreground/15 p-8"><p className="eyebrow text-[#8b4a38]">改造前</p>{before.map((item)=><p key={item} className="mt-4 flex gap-3 text-muted-foreground"><span>—</span>{item}</p>)}</div><div className="border border-foreground/15 bg-[#dff6e6] p-8"><p className="eyebrow text-[#147e66]">改造后</p>{after.map((item)=><p key={item} className="mt-4 flex gap-3"><Check className="size-5 shrink-0 text-[#147e66]"/>{item}</p>)}</div></div><div className="mt-10 grid gap-6 md:grid-cols-2"><article className="bg-[#071817] p-8 text-white"><span className="text-sm text-[#bff5d1]">专家调查能力</span><strong className="mt-4 block text-4xl font-black">3–4 个月 → 一周内</strong><p className="mt-3 text-white/55">复杂问题最快 2 天。</p></article><article className="bg-[#071817] p-8 text-white"><span className="text-sm text-[#bff5d1]">远程取证系统</span><strong className="mt-4 block text-4xl font-black">仍在生产运行</strong><p className="mt-3 text-white/55">3–5 名内部员工持续使用。</p></article></div><div className="mt-12 border-t border-foreground/20 pt-8"><p className="eyebrow text-[#147e66]">证据边界</p><p className="mt-4 max-w-4xl leading-8 text-muted-foreground">规模、流程与结果数据来自 Arthur 的任职经历总结及 NAS 内部演讲材料，事实核验日期为 2026-09-01。本页不代表 Deeper Network 对蓝旗鱼 AI 的客户授权、背书或合作关系；也不把任职期间成果计入蓝旗鱼客户交付数量。</p><Button nativeButton={false} render={<Link href="/about/arthur-guo"/>} variant="outline" className="mt-7 rounded-none">查看 Arthur 经历 <ArrowRight/></Button></div></div></section></main><SiteFooter/></>}
