'use client';
import { useMemo, useState } from 'react';
import { ArrowRight, Check, Copy, Printer, RotateCcw, TriangleAlert } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Progress, ProgressLabel, ProgressValue } from '@/components/ui/progress';

type Answer=0|1|2; type Question={text:string;critical?:boolean};
const groups:Array<{key:string;label:string;questions:Question[]}>= [
  {key:'value',label:'问题与价值',questions:[{text:'问题持续发生，并能用时间、收入、成本或风险描述损失'},{text:'成功可以用一到两个业务指标和当前基线核验'},{text:'首个范围可以在一个流程、团队或产品线内闭环'},{text:'即使不使用 AI，这个问题也值得企业投入解决'}]},
  {key:'evidence',label:'数据与证据',questions:[{text:'能提供代表性的真实数据、工作样本或历史记录'},{text:'数据来源、使用授权、敏感范围和保存方式已经明确',critical:true},{text:'可以建立测试集，并区分正确、错误与不可回答'},{text:'结果能够写回原工作流并留下可追溯记录'}]},
  {key:'owner',label:'负责人和采用',questions:[{text:'有一名业务负责人对结果、资源和跨部门协调负责',critical:true},{text:'一线使用者能够参与诊断、试用、反馈和验收'},{text:'上线后有人负责知识、规则、评估集与异常处理'},{text:'管理者接受从小范围验证，而不是一次覆盖全集团'}]},
  {key:'risk',label:'生产与风险',questions:[{text:'高风险输出、价格、承诺、审批和执行动作保留人工闸门',critical:true},{text:'系统错误时可以拒答、回退、暂停并恢复到原流程'},{text:'访问权限、操作日志、监控告警和责任边界可以落实'},{text:'已经定义 30 / 60 / 90 天复查与停止条件'}]}
];
const questions=groups.flatMap((group)=>group.questions.map((question)=>({...question,group:group.key,label:group.label})));
const options:Array<{value:Answer;label:string;detail:string}>=[{value:2,label:'已具备',detail:'有事实或材料可证明'},{value:1,label:'部分具备',detail:'方向明确但仍需补齐'},{value:0,label:'尚未具备',detail:'目前没有可核验证据'}];

export function ProjectDecisionScorer(){
  const [answers,setAnswers]=useState<Array<Answer|null>>(questions.map(()=>null)); const [copied,setCopied]=useState(false);
  const answered=answers.filter((answer)=>answer!==null).length; const total=answers.reduce<number>((sum,answer)=>sum+(answer??0),0); const score=Math.round(total/(questions.length*2)*100);
  const criticalFailures=questions.flatMap((question,index)=>question.critical&&answers[index]===0?[question.text]:[]);
  const dimensions=groups.map((group)=>{const indexes=questions.flatMap((question,index)=>question.group===group.key?[index]:[]);const points=indexes.reduce<number>((sum,index)=>sum+(answers[index]??0),0);return {...group,score:Math.round(points/(indexes.length*2)*100)};});
  const weakest=[...dimensions].sort((a,b)=>a.score-b.score)[0];
  const decision=useMemo(()=>{if(answered<questions.length)return ['待完成','完成全部 16 项后生成项目决策。'];if(criticalFailures.length>=2||score<30)return ['STOP','存在多个生产前提缺失。停止开发，重新定义问题或取消当前项目。'];if(criticalFailures.length===1||score<50)return ['HOLD','关键条件尚未成立。暂停开发，先解决红线问题并补齐证据。'];if(score<75)return ['ADJUST','方向可能成立，但需要收窄范围并补齐最低维度后再进入 MVD。'];return ['GO','主要前提已具备，可以进入资格确认并核验首个 MVD 边界。'];},[answered,score,criticalFailures.length]);
  const report=`蓝旗鱼 AI 项目决策报告\n\n决策：${decision[0]}\n得分：${score}/100\n完成：${answered}/${questions.length}\n关键红线：${criticalFailures.length?criticalFailures.join('；'):'无'}\n优先补齐：${weakest.label}（${weakest.score}/100）\n\n说明：${decision[1]}\n\n本报告用于项目初筛，不代替现场尽调、法律合规审查或正式投资决策。`;
  async function copy(){await navigator.clipboard.writeText(report);setCopied(true);setTimeout(()=>setCopied(false),1600)}
  return <div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><aside className="self-start bg-[#071817] p-8 text-white lg:sticky lg:top-24 print:static"><p className="eyebrow text-[#bff5d1]">实时决策报告</p><div className="mt-7 flex items-end gap-2"><strong className="text-7xl font-black text-[#bff5d1]">{score}</strong><span className="pb-3 text-white/45">/ 100</span></div><p className="mt-5 text-3xl font-black">{decision[0]}</p><p className="mt-3 leading-7 text-white/60">{decision[1]}</p><div className="mt-7 space-y-5 border-t border-white/15 pt-6">{dimensions.map((dimension)=><Progress key={dimension.key} value={dimension.score} className="gap-2 text-white"><ProgressLabel>{dimension.label}</ProgressLabel><ProgressValue>{dimension.score}</ProgressValue></Progress>)}</div><div className="mt-7 border-t border-white/15 pt-6"><p className="text-xs font-bold uppercase tracking-[.12em] text-[#bff5d1]">优先补齐</p><p className="mt-2 font-black">{weakest.label}</p>{criticalFailures.length>0&&<div className="mt-5 border border-[#ff9b8a]/40 p-4 text-sm text-[#ffb4a8]"><p className="flex items-center gap-2 font-bold"><TriangleAlert className="size-4"/>关键红线 {criticalFailures.length} 项</p>{criticalFailures.map((item)=><p key={item} className="mt-2 leading-6">{item}</p>)}</div>}</div></aside>
  <div>{groups.map((group,groupIndex)=><section key={group.key} className="mb-12"><div className="mb-5 flex items-end justify-between"><div><span className="text-xs font-bold text-[#147e66]">0{groupIndex+1}</span><h2 className="mt-1 text-2xl font-black">{group.label}</h2></div><span className="text-sm text-muted-foreground">{dimensions[groupIndex].score}/100</span></div><div className="space-y-5">{group.questions.map((question,questionIndex)=>{const index=groupIndex*4+questionIndex;return <fieldset key={question.text} className="border border-foreground/15 bg-white p-5"><legend className="px-2 font-bold leading-7">{question.text}{question.critical&&<span className="ml-2 text-xs text-[#a34532]">关键红线</span>}</legend><div className="mt-3 grid gap-2 sm:grid-cols-3">{options.map((option)=><button key={option.value} type="button" aria-pressed={answers[index]===option.value} onClick={()=>setAnswers((current)=>current.map((answer,i)=>i===index?option.value:answer))} className={`border p-3 text-left transition ${answers[index]===option.value?'border-[#147e66] bg-[#dff6e6]':'border-foreground/15 hover:border-foreground/40'}`}><span className="flex items-center gap-2 font-bold">{answers[index]===option.value&&<Check className="size-4 text-[#147e66]"/>}{option.label}</span><span className="mt-1 block text-xs text-muted-foreground">{option.detail}</span></button>)}</div></fieldset>})}</div></section>)}<div className="border-t border-foreground/20 pt-7"><p className="text-sm leading-6 text-muted-foreground">已完成 {answered}/{questions.length} 项。评分规则公开透明：已具备 2 分、部分具备 1 分、尚未具备 0 分；关键红线会降低决策等级。</p><div className="mt-6 flex flex-wrap gap-3"><Button nativeButton={false} render={<a href={`/apply?score=${score}&decision=${decision[0]}&source=project-scorer`}/>} className="h-12 rounded-none">提交报告，申请资格确认 <ArrowRight/></Button><Button variant="outline" onClick={copy} className="h-12 rounded-none">{copied?<Check/>:<Copy/>}{copied?'已复制':'复制报告'}</Button><Button variant="outline" onClick={()=>window.print()} className="h-12 rounded-none"><Printer/>打印保存</Button><Button variant="ghost" onClick={()=>setAnswers(questions.map(()=>null))} className="h-12 rounded-none"><RotateCcw/>重新评分</Button></div></div></div></div>;
}
