import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight } from 'lucide-react';
import { ArticleMeta } from '@/components/article-meta';
import { Button } from '@/components/ui/button';
import { PageHero, SiteFooter, SiteHeader } from '@/components/site-shell';
export const metadata:Metadata={title:'报价知识库与审批闭环｜脱敏交付记录',description:'中山某定制灯具企业报价知识库与审批项目的脱敏事实、交付路径、人机边界与证据限制。',alternates:{canonical:'/evidence/cases/quotation-approval'}};
const steps=[['建立价格记忆','按规格、数量、交期、币种和客户条件整理历史报价与供应商询价。'],['AI 生成草稿','调用最新规则和相似订单，形成成本依据、风险项与报价 PDF 草稿。'],['人工批准','负责人确认毛利、交期与例外条件后发出，并把最终结果写回价格记忆。']];
export default function Page(){return <><SiteHeader/><main><PageHero eyebrow="脱敏交付记录 · 2026.06" title="客户催的不是报价，而是确定性。" intro="中山某定制灯具企业的销售需要翻群找旧报价，采购经常重新询价，复制 Word 时还可能遗漏交期条件。项目把历史价格、成本依据、风险提示和审批结果接成闭环。"/><ArticleMeta title="报价知识库与审批闭环｜脱敏交付记录" description="价格记忆、报价草稿、风险提示与人工审批。" path="/evidence/cases/quotation-approval"/><section className="px-5 py-20 lg:px-10"><div className="mx-auto max-w-[1100px]"><div className="grid md:grid-cols-3">{steps.map(([title,detail],index)=><article key={title} className="border-t border-foreground/20 py-7 md:border-r md:px-6 first:pl-0"><span className="text-xs text-[#147e66]">0{index+1}</span><h2 className="mt-8 text-2xl font-black">{title}</h2><p className="mt-3 leading-7 text-muted-foreground">{detail}</p></article>)}</div><div className="mt-14 grid gap-8 bg-[#071817] p-8 text-white md:grid-cols-2"><div><p className="eyebrow text-[#bff5d1]">验收指标</p><p className="mt-4 leading-7 text-white/60">报价周期、漏项率、毛利底线、审批时长、历史报价复用率。</p></div><div><p className="eyebrow text-[#ff9b8a]">系统边界与证据限制</p><p className="mt-4 leading-7 text-white/60">价格、交期和商业承诺不自动发出。公开材料没有披露验收后的具体数值，因此本页不宣称报价效率或毛利已经改善多少。</p></div></div><Button nativeButton={false} render={<Link href="/solutions/customer-service-sales"/>} variant="outline" className="mt-8 rounded-none">查看客户服务与销售方案 <ArrowRight/></Button></div></section></main><SiteFooter/></>}
