export type SiteContentItem = {
  path: string;
  title: string;
  summary: string;
  kind: '品牌' | '方法' | '方案' | '证据' | '工具' | '知识' | '研究' | '转化';
};
export const siteContentUpdatedAt = '2026-09-01';
export const siteContent: SiteContentItem[] = [
  {
    path: '/',
    title: '蓝旗鱼 AI｜企业 AI 落地与 FDE',
    summary: '面向中国企业的 FDE 落地团队：诊断、MVD、生产部署、采用与复制。',
    kind: '品牌',
  },
  {
    path: '/fde',
    title: '什么是 FDE',
    summary: '解释 Forward Deployed Engineering 的定义、适用边界与交付方法。',
    kind: '方法',
  },
  {
    path: '/about/arthur-guo',
    title: '郭斌 Arthur',
    summary: '企业 AI 系统设计与 FDE 落地实践者的经历与方法立场。',
    kind: '品牌',
  },
  {
    path: '/training',
    title: 'Codex 与企业 AI 实战培训',
    summary: '建立共同语言、完成真实练习并发现候选 FDE 场景。',
    kind: '方法',
  },
  {
    path: '/partners',
    title: '合作伙伴与城市 FDE',
    summary: '合作角色、准入标准、协作闭环、退出规则与申请入口。',
    kind: '品牌',
  },
  {
    path: '/solutions',
    title: '行业与业务场景',
    summary: '从昂贵问题切入真实现场的行业方案目录。',
    kind: '方案',
  },
  {
    path: '/solutions/industry-associations',
    title: '产业协会与园区 AI 落地',
    summary: '知识、内容、会员服务与运营执行的分步落地。',
    kind: '方案',
  },
  {
    path: '/solutions/cross-border-ecommerce',
    title: '跨境电商 AI 落地',
    summary: '围绕询盘、退货与经营判断连接真实运营数据。',
    kind: '方案',
  },
  {
    path: '/solutions/manufacturing-supply-chain',
    title: '制造与供应链 AI 落地',
    summary: '围绕质量、交付、返工或报价异常建立行动闭环。',
    kind: '方案',
  },
  {
    path: '/solutions/customer-service-sales',
    title: '客户服务与销售 AI 落地',
    summary: '连接客户上下文、知识依据、跟进动作与结果写回。',
    kind: '方案',
  },
  {
    path: '/solutions/enterprise-knowledge',
    title: '企业知识库与经营决策',
    summary: '导入、治理、带来源查询与持续更新的知识闭环。',
    kind: '方案',
  },
  {
    path: '/evidence',
    title: '案例与证据',
    summary: '证据分级、生产实践、脱敏交付记录与公开规则。',
    kind: '证据',
  },
  {
    path: '/evidence/production-proof/deeper-network',
    title: 'Deeper Network 复杂售后调查系统',
    summary: 'Arthur 任职期间的远程取证与专家调查生产实践。',
    kind: '证据',
  },
  {
    path: '/evidence/case-template',
    title: 'FDE 案例证据模板',
    summary: '公开案例应覆盖的背景、基线、结果、限制与交接字段。',
    kind: '证据',
  },
  {
    path: '/evidence/cases',
    title: '脱敏交付记录',
    summary: '四项真实项目的交付路径、验收指标与证据限制。',
    kind: '证据',
  },
  {
    path: '/evidence/cases/return-root-cause',
    title: '退货利润归因与整改',
    summary: '订单生命线、原因证据链与整改闭环。',
    kind: '证据',
  },
  {
    path: '/evidence/cases/product-intelligence',
    title: '产品情报与开模决策',
    summary: '情报池、机会假设、小样验证与人工开模闸门。',
    kind: '证据',
  },
  {
    path: '/evidence/cases/sales-follow-up',
    title: '询盘识别与跟进闭环',
    summary: '统一上下文、AI 辅助判断与 CRM 动作写回。',
    kind: '证据',
  },
  {
    path: '/evidence/cases/quotation-approval',
    title: '报价知识库与审批闭环',
    summary: '价格记忆、报价草稿、风险提示与人工审批。',
    kind: '证据',
  },
  {
    path: '/diagnostic',
    title: 'FDE 适配度评估',
    summary: '用 12 项条件生成 GO、ADJUST 或 HOLD 初步报告。',
    kind: '工具',
  },
  {
    path: '/apply',
    title: '申请企业 AI 业务诊断',
    summary: '提交结构化真实问题，进入项目资格判断。',
    kind: '转化',
  },
  {
    path: '/tools',
    title: 'FDE 工具与模板',
    summary: '诊断、决策、五张地图、MVD 与案例证据工具目录。',
    kind: '工具',
  },
  {
    path: '/tools/project-decision-scorer',
    title: 'AI 项目决策评分器',
    summary: '16 项生产条件与关键红线，生成四级项目决策。',
    kind: '工具',
  },
  {
    path: '/tools/five-maps',
    title: '企业 AI 诊断五张地图',
    summary: '问题、流程、数据、责任和风险五张地图。',
    kind: '工具',
  },
  {
    path: '/tools/mvd-designer',
    title: 'MVD 设计器',
    summary: '把问题、基线、数据、人机边界和成功条件写成一页草案。',
    kind: '工具',
  },
  {
    path: '/knowledge',
    title: 'FDE 知识库',
    summary: '企业 AI 落地定义、决策、方法、比较与风险的直接答案。',
    kind: '知识',
  },
  {
    path: '/knowledge/fde-vs-consulting-outsourcing',
    title: 'FDE 与咨询、外包有什么区别',
    summary: '比较目标、责任、交付物与业务结果闭环。',
    kind: '知识',
  },
  {
    path: '/knowledge/poc-vs-mvd',
    title: 'PoC 和 MVD 有什么区别',
    summary: 'PoC 证明技术可能，MVD 证明最小业务闭环值得部署。',
    kind: '知识',
  },
  {
    path: '/knowledge/rag-vs-agent',
    title: 'RAG 与 Agent 怎么选',
    summary: 'RAG 负责有依据地回答，Agent 在边界内执行动作。',
    kind: '知识',
  },
  {
    path: '/knowledge/training-vs-delivery',
    title: 'AI 培训与 AI 落地有什么区别',
    summary: '培训提升人的能力，FDE 改变真实工作流。',
    kind: '知识',
  },
  {
    path: '/knowledge/general-saas-vs-fde',
    title: '通用 SaaS 与 FDE 怎么选',
    summary: '高共性流程优先 SaaS，高价值个性流程考虑 FDE。',
    kind: '知识',
  },
  {
    path: '/knowledge/how-to-choose-ai-project',
    title: '企业如何选择第一个 AI 项目',
    summary: '按问题价值、数据、负责人、范围和可核验结果选择。',
    kind: '知识',
  },
  {
    path: '/knowledge/why-ai-projects-fail',
    title: '企业 AI 项目为什么失败',
    summary: '问题不贵、数据不真、无人负责与无人采用是常见原因。',
    kind: '知识',
  },
  {
    path: '/knowledge/five-maps-method',
    title: '企业 AI 现场诊断的五张地图',
    summary: '用问题、流程、数据、责任与风险五张地图完成现场诊断。',
    kind: '知识',
  },
  {
    path: '/knowledge/mvd-design',
    title: '如何设计最小可行部署 MVD',
    summary: '用真实数据、真实使用者和生产边界验证最小业务闭环。',
    kind: '知识',
  },
  {
    path: '/knowledge/evaluation-set',
    title: '企业 AI 项目如何建立评估集',
    summary: '用固定真实任务、期望结果和评分规则持续验证系统。',
    kind: '知识',
  },
  {
    path: '/knowledge/production-guardrails',
    title: '企业 AI 系统需要哪些生产护栏',
    summary: '数据权限、输出依据、行动边界、人工审核、监控与回退。',
    kind: '知识',
  },
  {
    path: '/knowledge/adoption-handover',
    title: '企业 AI 项目如何推动采用与交接',
    summary: '工作流、负责人、反馈、运营资产与 30/60/90 天复查。',
    kind: '知识',
  },
  {
    path: '/knowledge/fde-readiness',
    title: '什么企业适合 FDE',
    summary: '用昂贵问题、真实数据、负责人、范围和结果压力判断 FDE 适配度。',
    kind: '知识',
  },
  {
    path: '/knowledge/ai-business-diagnostic',
    title: '企业 AI 业务诊断怎么做',
    summary: '从真实损失核验流程、数据、责任、风险和最小部署边界。',
    kind: '知识',
  },
  {
    path: '/knowledge/ai-project-baseline',
    title: '企业 AI 项目如何建立业务基线',
    summary: '固定任务、周期、质量、成本与结果口径，使改善可比较。',
    kind: '知识',
  },
  {
    path: '/knowledge/time-to-value',
    title: '企业 AI 项目如何衡量 TTV',
    summary: '从项目启动计算到首个可核验业务价值，并拆解等待时间。',
    kind: '知识',
  },
  {
    path: '/knowledge/human-ai-boundary',
    title: '企业 AI 项目如何划分人机边界',
    summary: '按动作与错误代价定义自动、审核、拒绝、升级与禁止边界。',
    kind: '知识',
  },
  {
    path: '/knowledge/production-acceptance',
    title: '企业 AI 项目如何做生产验收',
    summary: '同时验收业务结果、任务、运行、护栏、采用与交接。',
    kind: '知识',
  },
  {
    path: '/knowledge/ai-project-portfolio',
    title: '企业如何管理 AI 项目组合',
    summary: '统一项目排序、阶段投入、停止机制和资产复用指标。',
    kind: '知识',
  },
  {
    path: '/research',
    title: '企业 AI / FDE 公开研究',
    summary: '原创问题集、测量协议、公开数据与方法研究目录。',
    kind: '研究',
  },
  {
    path: '/research/fde-query-benchmark',
    title: '中文企业 AI / FDE 基准查询集',
    summary: '120 个公开问题与可重复的 GEO 测量方法。',
    kind: '研究',
  },
  {
    path: '/research/geo-measurement-protocol',
    title: 'GEO 月度测量协议与空白模板',
    summary: '9 个平台、1080 行记录和公开指标定义。',
    kind: '研究',
  },
];
