import type { Metadata } from 'next';
import Link from '@/components/safe-link';
import { ArrowRight } from 'lucide-react';
import { ArticleMeta } from '@/components/article-meta';
import { Button } from '@/components/ui/button';
import { PageHero, SiteFooter, SiteHeader } from '@/components/site-shell';
export const metadata:Metadata={title:'产品情报与开模决策｜脱敏交付记录',description:'东莞某消费品企业产品情报与开模决策项目的脱敏事实、交付路径、人工闸门与证据限制。',alternates:{canonical:'/evidence/cases/product-intelligence'}};
const steps=[['收集信号','把差评主题、竞品价格、节日信号和历史销售表现放进同一情报池。'],['形成假设','AI 从碎片信息中整理需求主题、机会证据、风险和待验证问题。'],['人工闸门','产品、供应链与财务先做小样、小单验证，开模仍由负责人批准。']];
export default function Page(){return <><SiteHeader/><main><PageHero eyebrow="脱敏交付记录 · 2026.04" title="开模最贵的，是判断错了方向。" intro="东莞某消费品企业过去用一到两个月人工收集评论与竞品信息，约十套开模中有三款形成滞销。项目目标不是让 AI 自动选品，而是让投入决策建立在可追溯信号与小样验证上。"/><ArticleMeta title="产品情报与开模决策｜脱敏交付记录" description="情报池、机会假设、小样验证与人工开模闸门。" path="/evidence/cases/product-intelligence"/><section className="px-5 py-20 lg:px-10"><div className="mx-auto max-w-[1100px]"><div className="grid gap-6 border-y border-foreground/15 py-7 sm:grid-cols-4"><div><span className="text-xs text-muted-foreground">人工收集周期</span><strong className="mt-2 block text-2xl">1–2 个月</strong></div><div><span className="text-xs text-muted-foreground">评论样本</span><strong className="mt-2 block text-2xl">100+ 条</strong></div><div><span className="text-xs text-muted-foreground">开模规模</span><strong className="mt-2 block text-2xl">约 10 套</strong></div><div><span className="text-xs text-muted-foreground">历史滞销</span><strong className="mt-2 block text-2xl">3 款</strong></div></div><div className="mt-14 grid md:grid-cols-3">{steps.map(([title,detail],index)=><article key={title} className="border-t border-foreground/20 py-7 md:border-r md:px-6 first:pl-0"><span className="text-xs text-[#147e66]">0{index+1}</span><h2 className="mt-8 text-2xl font-black">{title}</h2><p className="mt-3 leading-7 text-muted-foreground">{detail}</p></article>)}</div><div className="mt-14 grid gap-8 bg-[#071817] p-8 text-white md:grid-cols-2"><div><p className="eyebrow text-[#bff5d1]">验收指标</p><p className="mt-4 leading-7 text-white/60">情报整理周期、有效需求主题、小样验证通过率、滞销风险复盘。</p></div><div><p className="eyebrow text-[#ff9b8a]">证据限制</p><p className="mt-4 leading-7 text-white/60">上述数字是项目启动时的现场事实，不是项目改善结果。公开材料没有客户授权证言及部署后的量化数据。</p></div></div><Button nativeButton={false} render={<Link href="/solutions/cross-border-ecommerce"/>} variant="outline" className="mt-8 rounded-none">查看跨境电商方案 <ArrowRight/></Button></div></section></main><SiteFooter/></>}
