import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, Check, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PageHero, SiteFooter, SiteHeader } from '@/components/site-shell';

export const metadata: Metadata = { title: '什么是 FDE', description: 'Forward Deployed Engineering 的定义、适用边界，以及与咨询、外包和解决方案架构师的区别。', alternates:{canonical:'/fde'} };
const compare = [['传统咨询','提供判断与建议','建议可能停留在报告'],['定制外包','按需求交付功能','容易与业务结果脱节'],['解决方案架构','设计技术方案','通常不持续负责采用'],['蓝旗鱼 FDE','从损失出发，诊断、开发并推动采用','范围必须聚焦，双方需共同投入']];
export default function FdePage(){return <><SiteHeader/><main><PageHero eyebrow="直接回答" title="FDE 是什么？" intro="FDE（Forward Deployed Engineering）是一种由工程师直接进入客户真实业务现场，与业务人员共同发现问题、接触数据、构建系统并推动采用的交付方式。它的核心不是驻场，而是对可核验业务结果负责。"/><section className="px-5 py-22 lg:px-10"><div className="mx-auto max-w-[1500px]"><div className="grid gap-10 lg:grid-cols-2"><div><p className="eyebrow text-[#147e66]">适用条件</p><h2 className="mt-4 text-4xl font-black tracking-[-.04em] lg:text-6xl">什么时候应该选择 FDE？</h2></div><div className="space-y-3">{['问题跨越多个系统或部门，无法靠标准 SaaS 直接解决','需要在不完整、混乱的真实数据中建立可用闭环','业务结果取决于人员采用，而不只是功能上线','企业愿意提供负责人、数据与一线验证条件'].map(x=><p key={x} className="flex gap-3 border-t border-foreground/15 py-4 text-lg"><Check className="shrink-0 text-[#147e66]"/>{x}</p>)}</div></div><div className="mt-20 overflow-x-auto"><table className="w-full min-w-3xl border-collapse text-left"><thead><tr className="border-b-2 border-foreground"><th className="py-4">交付方式</th><th>主要产出</th><th>典型局限</th></tr></thead><tbody>{compare.map(r=><tr key={r[0]} className="border-b border-foreground/15"><th className="py-5 text-lg">{r[0]}</th><td>{r[1]}</td><td className="text-muted-foreground">{r[2]}</td></tr>)}</tbody></table></div></div></section><section className="bg-[#dff6e6] px-5 py-22 lg:px-10"><div className="mx-auto grid max-w-[1500px] gap-12 lg:grid-cols-2"><div><p className="eyebrow text-[#147e66]">不适用边界</p><h2 className="mt-4 text-4xl font-black tracking-[-.04em] lg:text-6xl">这些情况，先不要做。</h2></div><div className="space-y-3">{['只是为了展示 AI 概念，没有真实使用者','没有业务负责人，也无法定义当前损失','拒绝提供任何真实数据，却要求承诺结果','希望一次性完成“AI 赋能全集团”'].map(x=><p key={x} className="flex gap-3 border-t border-foreground/15 py-4 text-lg"><X className="shrink-0 text-[#ff735d]"/>{x}</p>)}<Button render={<Link href="/diagnostic"/>} size="lg" className="mt-4 h-12 rounded-none">做一次适配度自检 <ArrowRight/></Button></div></div></section></main><SiteFooter/></>}
