import type { Metadata } from 'next';
import Link from '@/components/safe-link';
import { ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PageHero, SiteFooter, SiteHeader } from '@/components/site-shell';
export const metadata:Metadata={title:'案例与证据',description:'蓝旗鱼 AI 的证据分级、生产实践、脱敏交付记录与公开证据规则。',alternates:{canonical:'/evidence'}};
const levels=[['已验证案例','存在客户授权、明确基线和结果数据，可被核验。'],['脱敏案例','真实项目，但客户身份或敏感数据经过处理。'],['真实交付记录','存在项目材料与验收口径，但公开结果受到授权限制。'],['内部实践','在蓝旗鱼自身流程中真实运行并有使用记录。'],['演示原型','用于解释技术路径，不代表客户成功。'],['待验证假设','基于现场观察提出，尚未完成数据验证。']];
const assets=[['4 项脱敏 FDE 交付记录','真实交付材料','覆盖退货归因、产品情报、询盘跟进和报价审批，公开交付路径、验收指标与证据限制。'],['产业协会 FDE 合作方案','真实方案材料','明确 3—8 周交付周期、资料量上限、真实场景验收、人工审核和升级边界。'],['FDE 客户现场访谈与尽调表','独家方法资产','24 页结构化尽调框架，用于核验问题、流程、数据、风险和组织条件。'],['Codex 初阶与实战课程','培训资产','培训不被包装为生产部署案例。']];
export default function Evidence(){return <><SiteHeader/><main><PageHero eyebrow="信任证据系统" title="原型就是原型。结果必须可核验。" intro="没有授权和数据时，蓝旗鱼不会把演示包装成客户成功。每项公开证据都标明来源、边界、时间与验证状态。"/><section className="px-5 py-20 lg:px-10"><div className="mx-auto max-w-[1500px]"><h2 className="text-4xl font-black tracking-[-.04em] lg:text-6xl">证据分级</h2><div className="mt-10 grid md:grid-cols-3 lg:grid-cols-6">{levels.map(([title,detail],index)=><article key={title} className="border-t border-foreground/20 py-6 md:border-r md:px-5 first:pl-0"><span className="text-xs text-[#3657d6]">0{index+1}</span><h3 className="mt-8 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{detail}</p></article>)}</div><h2 className="mt-24 text-4xl font-black tracking-[-.04em] lg:text-6xl">当前可核验资产</h2><div className="mt-10">{assets.map(([title,kind,detail],index)=><article key={title} className="grid gap-5 border-t border-foreground/20 py-8 lg:grid-cols-[80px_1fr_1fr_2fr]"><span className="text-sm text-[#3657d6]">0{index+1}</span><h3 className="text-xl font-black">{title}</h3><b className="text-sm text-[#3657d6]">{kind}</b><p className="leading-7 text-muted-foreground">{detail}</p></article>)}</div><div className="mt-14 grid gap-5 md:grid-cols-2"><div className="bg-[#f1eee5] p-8"><h2 className="text-3xl font-black">案例证据标准</h2><p className="mt-3 leading-7 text-muted-foreground">公开案例必须覆盖背景、流程、损失、数据、MVD、结果与限制。</p><Button nativeButton={false} render={<Link href="/evidence/case-template"/>} variant="outline" className="mt-6 h-12 rounded-none bg-transparent">查看 12 项模板 <ArrowRight/></Button></div><div className="bg-[#0b1238] p-8 text-white"><h2 className="text-3xl font-black">脱敏交付记录</h2><p className="mt-3 leading-7 text-white/55">没有量化结果时明确说明证据限制。</p><Button nativeButton={false} render={<Link href="/evidence/cases"/>} className="mt-6 h-12 rounded-none bg-[#cdd5ff] text-[#0b1238] hover:bg-[#e4e8ff]">进入交付记录 <ArrowRight/></Button></div></div></div></section></main><SiteFooter/></>}
