import type { Metadata } from 'next';
import Link from '@/components/safe-link';
import { ArrowRight, Check, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PageHero, SiteFooter, SiteHeader } from '@/components/site-shell';
export const metadata:Metadata={title:'Codex 与企业 AI 实战培训',description:'面向企业管理者和一线骨干的 Codex 与企业 AI 实战培训：建立共同语言、完成真实练习、发现可进入 FDE 诊断的候选场景。',alternates:{canonical:'/training'}};
const modules=[['01 建立共同语言','理解 Codex、智能体、自动化与企业 AI 落地的差异，避免把聊天演示当成生产系统。'],['02 工具基础训练','在安全边界内完成文件、资料、分析和内容等个人工作任务，形成可复查的操作习惯。'],['03 真实机器人演示','观察飞书、企业微信与个人微信机器人如何连接入口、知识和工作动作，并讨论权限边界。'],['04 业务场景实操','从学员自己的重复工作出发，写清输入、输出、人工判断与成功条件，完成一项可展示练习。'],['05 场景筛选与复盘','区分个人提效、团队工具与企业生产部署，选出需要进一步现场诊断的高价值问题。']];
const outputs=['一份个人或岗位 AI 工作样例','一张候选场景清单与优先级','至少一个问题的输入、输出和人机边界','需要进一步补齐的数据、权限与责任条件'];
export default function Page(){const courseSchema={'@context':'https://schema.org','@type':'Course',name:'蓝旗鱼 Codex 与企业 AI 实战培训',description:metadata.description,provider:{'@type':'Organization',name:'蓝旗鱼 AI',url:'https://bluefin-ai.cn'},inLanguage:'zh-CN'};return <><SiteHeader/><main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(courseSchema)}}/><PageHero eyebrow="企业能力建设 · 实战培训" title="培训让人会用，FDE 让业务产生结果。" intro="蓝旗鱼把培训作为共同语言、种子用户和场景发现的入口。课程要求学员动手完成真实练习，但不会把课堂 Demo 包装成企业 AI 已经落地。"/>
  <section className="px-5 py-20 lg:px-10"><div className="mx-auto grid max-w-[1300px] gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow text-[#147e66]">课程依据</p><h2 className="mt-5 text-4xl font-black tracking-[-.04em] lg:text-6xl">来自真实初阶与实操课程资产。</h2><p className="mt-6 leading-8 text-muted-foreground">本页课程结构基于 NAS 中《Codex 初阶培训—实战课》和《Codex 初阶实操》两套授课文件整理。已核验内容包括工具入门、现场机器人演示、企业微信与飞书入口、学员作品展示和企业场景练习。</p></div><div className="grid gap-px bg-foreground/15 sm:grid-cols-2"><article className="bg-[#dff6e6] p-8"><span className="text-xs font-bold text-[#147e66]">适合</span><h3 className="mt-5 text-2xl font-black">管理者与业务骨干</h3><p className="mt-3 leading-7 text-muted-foreground">希望建立共同语言、形成内部种子用户，并发现真实业务候选场景的团队。</p></article><article className="bg-[#f1eee5] p-8"><span className="text-xs font-bold text-[#8b4a38]">不适合</span><h3 className="mt-5 text-2xl font-black">把培训当作系统交付</h3><p className="mt-3 leading-7 text-muted-foreground">如果目标是接入企业数据、重构流程或承担生产结果，应直接进入 FDE 诊断。</p></article></div></div></section>
  <section className="bg-[#071817] px-5 py-20 text-white lg:px-10"><div className="mx-auto max-w-[1300px]"><p className="eyebrow text-[#bff5d1]">建议课程结构</p><h2 className="mt-5 text-4xl font-black tracking-[-.04em] lg:text-6xl">从理解工具，到发现可落地问题。</h2><div className="mt-12">{modules.map(([title,detail])=><article key={title} className="grid gap-4 border-t border-white/15 py-7 md:grid-cols-[240px_1fr]"><h3 className="text-xl font-black text-[#bff5d1]">{title}</h3><p className="leading-7 text-white/60">{detail}</p></article>)}</div></div></section>
  <section className="px-5 py-20 lg:px-10"><div className="mx-auto grid max-w-[1300px] gap-12 lg:grid-cols-2"><div><p className="eyebrow text-[#147e66]">课程产出</p><h2 className="mt-5 text-4xl font-black">不只听懂，还要留下可继续使用的材料。</h2><div className="mt-8 space-y-4">{outputs.map((output)=><p key={output} className="flex gap-3 border-t border-foreground/15 pt-4"><Check className="size-5 shrink-0 text-[#147e66]"/>{output}</p>)}</div></div><div className="border border-foreground/15 p-8"><p className="eyebrow text-[#8b4a38]">课程不承诺</p><div className="mt-6 space-y-4 text-muted-foreground">{['不承诺一次培训完成企业 AI 转型','不承诺课堂原型可以直接进入生产','不在缺少真实数据时承诺降本、增收或采用率','不代替数据合规、安全评审和系统集成'].map((item)=><p key={item} className="flex gap-3 leading-7"><X className="mt-1 size-4 shrink-0 text-[#8b4a38]"/>{item}</p>)}</div></div></div></section>
  <section className="bg-[#dff6e6] px-5 py-18 lg:px-10"><div className="mx-auto grid max-w-[1300px] gap-10 lg:grid-cols-[1.1fr_.9fr]"><div><p className="eyebrow text-[#147e66]">培训之后</p><h2 className="mt-4 text-4xl font-black tracking-[-.04em]">候选场景 → 适配度评估 → 现场诊断 → MVD</h2><p className="mt-5 max-w-3xl leading-8 text-muted-foreground">只有问题价值、真实数据、负责人和生产边界同时成立，课堂场景才进入部署评估。其余练习保留为个人或团队能力资产。</p></div><div className="flex flex-col justify-center gap-3"><Button nativeButton={false} render={<Link href="/apply?source=training"/>} className="h-12 rounded-none">申请企业内训沟通 <ArrowRight/></Button><Button nativeButton={false} render={<Link href="/diagnostic"/>} variant="outline" className="h-12 rounded-none bg-transparent">先做 FDE 适配度评估</Button></div></div></section></main><SiteFooter/></>}
